### ISSUE TITLE
cluster_layout: clarify where the master is located

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/doc#14]
Currently, only `Managed by MAMID` in the upper right gives a hint on where the master is located.

Maybe update the text `Managed by MAMID master instance.

Better: have a master box with connections to all the slaves (probably hard to draw without producing spaghetti)

**Comment by antonxy** [comment]
#19 passt so? 
![screenshot from 2016-06-04 13-42-31](https://cloud.githubusercontent.com/assets/4194320/15799364/43736068-2a5a-11e6-889c-aeed437a8eb0.png)

**Comment by problame** [comment]
Jo.
