### ISSUE TITLE
GUI: UML Class Diagram

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/doc#29]
Use UML sub-packages for external libraries!
Research a little on how e.g. AngluarJS is represented in class diagrams... (-> other PSE projects?)

**Comment by janisstreib** [comment]
First attemt in 8ec3a0366b32dc57d57d7930f0181ebd70cd618b 
https://github.com/KIT-MAMID/doc/blob/8ec3a0366b32dc57d57d7930f0181ebd70cd618b/design/gui.uxf
